# Generated by Django 5.1.1 on 2024-09-06 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bp',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinLengthValidator(80), django.core.validators.MaxLengthValidator(120)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
